### ISSUE TITLE
DataStream.distribute causes ReferenceError when using external function inside

### ISSUE THREAD

**Issue by f1ames** [scramjetorg/scramjet#118]
**Basics**

`DataStream.distribute`

Reported on our Discord channel - https://discord.com/channels/925384545342201896/935178596304191549/953607695779364974.

**Describe the bug**

When trying to use external function in `distribute` method, it causes `ReferenceError`. And this is according to our official example here - https://framework.scramjet.org/docs/multi-threading.

This can be reproduce with the code (see on [RunKit](https://runkit.com/embed/l5yjgaihurli)):

```js
const { DataStream } = require('scramjet');

const echo = (val) => {
    return val;
};

DataStream.fromArray([1,2,3,4,5])
    .distribute((stream) => stream.map(echo))
    .map(console.log)
    .run()
```

And it results with multiple `ReferenceError: echo is not defined` errors.

**Expected behavior**

Well, if it's in our examples I would expect it should work. Or Documentation should clearly state that it couldn't be done this way.

**Test case**

See above.

**System:**

It was reported by the user using:

 - OS: Linux
 - Node version: 16

**Comment by MichalCz** [comment]
Sadly this is how the solution works - unless a `cluster.fork` based stream worker is written, this will not be able to run as above. Distribute starts a separate process and that process receives only the body of the given method.
