### ISSUE TITLE
Cannot stop instance

### ISSUE THREAD

**Issue by tomkeee** [scramjetorg/scramjet#124]
I have a few instances that failed to start and, as a result, they have a status of ,,Failed to stop" (as shown below).

Is there a way to stop them permanently? I tried using `si inst kill <instance id>` , but it does not work.

![Zrzut ekranu z 2022-09-16 11-10-29](https://user-images.githubusercontent.com/80860556/190601927-42084001-f979-47dc-a05c-9314bf2e8971.png)

**Comment by alicja-gruzdz** [comment]
Hi @tomkeee :)

thank you for submitting this error. Unfortunately, this issue must be resolved by our backend team. I have already assigned someone to clear the list of your Instances, and furthermore we are working on fixing this issue permanently.

We will let you know as soon as the Instances are cleared and also later when we resolve the issue. 

Thank you for reporting once again.

**Comment by alicja-gruzdz** [comment]
The Instances have been cleared, please give it a try.

Unfortunately, you will need to send your Sequences to the SCP once again. 

I'm linking here the issue we suspect caused this problem and we are already working on resolving it as soon as possible; https://github.com/scramjetorg/transform-hub/issues/478

**Comment by tomkeee** [comment]
Now they are cleared. Thanks for help!
