### ISSUE TITLE
Runner failed error

### ISSUE THREAD

**Issue by tomkeee** [scramjetorg/scramjet#127]
I was trying to launch a few instances of the same sequence. The first two instances launch successfully, yet when I try to launch the third instance I keep getting the error shown below:
`Error: { message: 'Runner failed', exitcode: 213 }`

**Comment by daro1337** [comment]
Hi, @tomkeee, after analyzing the logs, you have exceeded the limit of running instances. By default Beta users can run 5 instances in parallel. Due to your contribution, we will double you this limit to 10 instances :)

**Comment by tomkeee** [comment]
Thanks a lot !
